### ISSUE TITLE
A tutorial to to use NIcheformer to generate the predicted spatial labels in the fine-tuning tasks

### ISSUE THREAD

**Issue by Luosanj** [theislab/nicheformer#3]
Hi, 
    Truly appreciate this excellent work! May you provide a tutorial for: how to get the predicted spatial labels with an input of spatial transcriptomics data? Thanks!

**Comment by Luosanj** [comment]
I hope to input the transcriptomic data into nicheformer and output the result of the downstream fine-tuning tasks. not sure if I can access the checkpoint repository.

**Comment by Luosanj** [comment]
Found finally. No issue now.

**Comment by StanislavBratchikov** [comment]
Hello @Luosanj! Can you kindly share the notebook link? I am having a hard time finding it. Thanks!
