### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by xim2016** [theislab/nicheformer#4]
Dear Nicheformer authors,

We are exceited to see your new released nichefomrer model which can be used as the fundation or backbone of single cell deep learning training for downstearm task.  Would you kindly provide your pretrained model and usage document to benefit the reader and in turn make your model more infuential. 

Thank you
Rena

**Comment by AnnaChristina** [comment]
Hi @xim2016,

thanks for your interest in using nicheformer!

We are sharing pretraining weights through mendeley data. A draft version can be accessed here:
https://data.mendeley.com/preview/87gm9hrgm8?a=d95a6dde-e054-4245-a7eb-0522d6ea7dff

I will also add this information to the readme so it's easier accessible! thanks!

I am closing your comment as resolved, but feel free to open it again in case of further questions!
